version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - backend

  backend:
    build: ./auth_service
    ports:
      - "8000:8000"
    command: /bin/bash -c "uvicorn main:app --reload --port 8000 --host=0.0.0.0 --log-level=info"
    volumes:
      - ./auth_service:/auth_service

  product:
    build: ./product_service
    ports:
      - "8001:8001"
    command: /bin/bash -c "uvicorn main:app --reload --port 8000 --host=0.0.0.0 --log-level=info"
    volumes:
      - ./product_service:/product_service
  
  service:
    build: ./user_service
    ports:
      - "8002:8002"
    command: /bin/bash -c "uvicorn main:app --reload --port 8000 --host=0.0.0.0 --log-level=info"
    volumes:
      - ./user_service:/user_service
  app:
    build: ./app
    ports:
      - "8003:8003"
    command: /bin/bash -c "uvicorn main:app --reload --port 8000 --host=0.0.0.0 --log-level=info"
    volumes:
      - ./app:/app

  db:
    image: postgres:17-alpine
    container_name: db
    volumes:
      - ./data/database/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: lab3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ufhybnehf23
    restart: unless-stopped

  adminer:
    image: adminer:4.7.9
    container_name: adminer
    ports:
      - 8090:8080
    depends_on:
      - db
    restart: unless-stopped

